name: TrainCarts2
version: ${project.version}
dev-url: ${project.url}
build: ${project.build.number}
description: Rewrite of TrainCarts, used for automatic metro in Cashcraft.
authors: [Movies22, bergerkiller]
api-version: 1.13
softdepend: [BKCommonLib, SignLink]
classdepend: [TAB]

main: com.bergerkiller.bukkit.tc.Preloader
preloader:
    main: com.movies22.cashcraft.tc.TrainCarts
    hastebinServer: https://paste.traincarts.net
    commands: [tc2]
    depend:
        BKCommonLib: https://www.spigotmc.org/resources/bkcommonlib.39590/
commands:
    tc2:
        description: Manages TrainCarts 2
        usage: /tc2 [reload/about]
        permission: tc2.command.tc2
    station:
        description: Manages TC2 stations. 
        usage: /station [list/info]
        permission: tc2.command.station
    depot:
        description: Manages TC2 depots. 
        usage: /depot [create/list/info/route/remove]
        permission: tc2.command.depot
    route:
        description: Manages TC2 routes.
        usage: /route [create/list/remove/configure/reroute/stations] 
        permission: tc2.command.route
    line:
        description: Manages TC2 metro lines.
        usage: /line [list/info] 
        permission: tc2.command.line
    train:
        description: Gets the total count of trains.
        usage: /train [line]
        permission: tc2.command.train